# Unofficial grok-mcp installer for Windows PowerShell
#   irm https://raw.githubusercontent.com/zai-one/grok-mcp/main/scripts/install.ps1 | iex
# Or:
#   .\scripts\install.ps1 -Project $env:USERPROFILE\code\myapp

param(
  [string]$Project = "$env:USERPROFILE",
  [string]$HomeDir = "$env:LOCALAPPDATA\grok-mcp"
)

$ErrorActionPreference = "Stop"
Write-Host "Unofficial grok-mcp installer (not xAI/Grok official)" -ForegroundColor Yellow

function Need-Cmd($name) {
  if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
    throw "Missing command: $name"
  }
}

Need-Cmd git
if (-not (Get-Command python -ErrorAction SilentlyContinue) -and -not (Get-Command py -ErrorAction SilentlyContinue)) {
  Write-Host "Python 3.10+ not found. Install from https://www.python.org/downloads/ (check 'Add to PATH'), then re-run." -ForegroundColor Red
  exit 1
}
$py = if (Get-Command py -ErrorAction SilentlyContinue) { "py -3" } else { "python" }

if (-not (Test-Path "$HomeDir\.git")) {
  New-Item -ItemType Directory -Force -Path (Split-Path $HomeDir) | Out-Null
  git clone --depth 1 https://github.com/zai-one/grok-mcp.git $HomeDir
} else {
  git -C $HomeDir pull --ff-only
}

Push-Location $HomeDir
& $py -m venv .venv
& .\.venv\Scripts\python.exe -m pip install -U pip
& .\.venv\Scripts\python.exe -m pip install -e ".[test]"

$lanes = Join-Path (Split-Path $Project -Parent) ".grok-mcp-lanes"
New-Item -ItemType Directory -Force -Path $lanes | Out-Null
$cfg = Join-Path $env:USERPROFILE ".config\grok-mcp"
New-Item -ItemType Directory -Force -Path $cfg | Out-Null
$envFile = Join-Path $cfg "env.ps1"
@"
# Generated by install.ps1 — no OAuth secrets
`$env:GROK_DELEGATE_ALLOWED_ROOTS = '$Project'
`$env:GROK_DELEGATE_LANES_PARENT = '$lanes'
`$env:GROK_DELEGATE_ECONOMY = '1'
`$env:GROK_DELEGATE_ECONOMY_COMPACT_POLL = '1'
"@ | Set-Content -Path $envFile -Encoding UTF8

Write-Host "Installed to $HomeDir" -ForegroundColor Green
Write-Host "Env: $envFile"
Write-Host ""
Write-Host "REQUIRED next steps:" -ForegroundColor Yellow
Write-Host "  1) Install Grok CLI and run: grok login"
Write-Host "  2) . $envFile; $HomeDir\.venv\Scripts\python.exe -m grok_delegate --self-test"
Write-Host "  3) Point Claude/Cursor MCP command at: $HomeDir\.venv\Scripts\grok-delegate.exe"
Pop-Location
