# Unofficial grok-mcp installer for Windows PowerShell
#   irm https://raw.githubusercontent.com/zai-one/grok-mcp/main/scripts/install.ps1 | iex
# Or:
#   .\scripts\install.ps1 -Project $env:USERPROFILE\code\myapp

param(
  [string]$Project = "$env:USERPROFILE",
  [string]$HomeDir = "$env:LOCALAPPDATA\grok-mcp"
)

$ErrorActionPreference = "Stop"
Write-Host "Unofficial grok-mcp installer (not xAI/Grok official)" -ForegroundColor Yellow

function Need-Cmd($name) {
  if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
    throw "Missing command: $name"
  }
}

Need-Cmd git
if (-not (Get-Command python -ErrorAction SilentlyContinue) -and -not (Get-Command py -ErrorAction SilentlyContinue)) {
  Write-Host "Python 3.10+ not found. Install from https://www.python.org/downloads/ (check 'Add to PATH'), then re-run." -ForegroundColor Red
  exit 1
}
$py = if (Get-Command py -ErrorAction SilentlyContinue) { "py -3" } else { "python" }

if (-not (Test-Path "$HomeDir\.git")) {
  New-Item -ItemType Directory -Force -Path (Split-Path $HomeDir) | Out-Null
  git clone --depth 1 https://github.com/zai-one/grok-mcp.git $HomeDir
} else {
  git -C $HomeDir pull --ff-only
}

Push-Location $HomeDir
& $py -m venv .venv
& .\.venv\Scripts\python.exe -m pip install -U pip
& .\.venv\Scripts\python.exe -m pip install -e ".[test]"

$lanes = Join-Path (Split-Path $Project -Parent) ".grok-mcp-lanes"
New-Item -ItemType Directory -Force -Path $lanes | Out-Null
$cfg = Join-Path $env:USERPROFILE ".config\grok-mcp"
New-Item -ItemType Directory -Force -Path $cfg | Out-Null
$envFile = Join-Path $cfg "env.ps1"
@"
# Generated by install.ps1 — no OAuth secrets
`$env:GROK_DELEGATE_ALLOWED_ROOTS = '$Project'
`$env:GROK_DELEGATE_LANES_PARENT = '$lanes'
`$env:GROK_DELEGATE_ECONOMY = '1'
`$env:GROK_DELEGATE_ECONOMY_COMPACT_POLL = '1'
"@ | Set-Content -Path $envFile -Encoding UTF8

# MCP client snippets — parity with install.sh, which writes the same two files.
# docs/EASY.md tells operators to merge these, so both install paths must emit them.
#
# install.sh points its snippets at a wrapper that sources the env file first,
# which is why "env": {} is enough there. Windows has no such wrapper, so the
# snippets carry the environment themselves. Deliberately not an intermediate
# .cmd: an extra process in an stdio MCP path buys nothing and complicates
# shutdown, while MCP hosts support `env` natively. Without this the server
# starts with an empty allowlist and every repo-touching tool fails closed.
$mcpDir = Join-Path $cfg "mcp"
New-Item -ItemType Directory -Force -Path $mcpDir | Out-Null
$launcher = Join-Path $HomeDir ".venv\Scripts\grok-delegate.exe"

# ConvertTo-Json escapes backslashes and quotes in Windows paths for us.
$launcherJson = $launcher | ConvertTo-Json
$envJson = [ordered]@{
    GROK_DELEGATE_ALLOWED_ROOTS         = $Project
    GROK_DELEGATE_LANES_PARENT          = $lanes
    GROK_DELEGATE_ECONOMY               = "1"
    GROK_DELEGATE_ECONOMY_COMPACT_POLL  = "1"
} | ConvertTo-Json

@"
{
  "mcpServers": {
    "grok-delegate": {
      "command": $launcherJson,
      "args": [],
      "env": $envJson
    }
  }
}
"@ | Set-Content -Path (Join-Path $mcpDir "claude_desktop.snippet.json") -Encoding UTF8

@"
{
  "mcpServers": {
    "grok-delegate": {
      "command": $launcherJson,
      "args": [],
      "env": $envJson
    }
  }
}
"@ | Set-Content -Path (Join-Path $mcpDir "cursor.snippet.json") -Encoding UTF8

Write-Host "Installed to $HomeDir" -ForegroundColor Green
Write-Host "Env: $envFile"
Write-Host "Client snippets: $mcpDir"
Write-Host ""
Write-Host "REQUIRED next steps:" -ForegroundColor Yellow
Write-Host "  1) Install Grok CLI and run: grok login"
Write-Host "  2) . $envFile; $HomeDir\.venv\Scripts\python.exe -m grok_delegate --self-test"
Write-Host "  3) Merge JSON from $mcpDir\claude_desktop.snippet.json into your MCP host,"
Write-Host "     then restart it and call grok_agent_status"
Pop-Location
